type Asset {
  id: String!
  name: String!
  slug: String!
  symbol: String!
}

type AssetResponse {
  asset: Asset
}

type AssetError {
  error: String!
}

type AssetNotFound {
  symbol: String!
}

input AssetInput {
  symbol: String!
}

union AssetResult = AssetResponse | AssetNotFound | AssetError

extend type Query {
  asset(input: AssetInput!): AssetResult!
}
